// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMj4rXwgFADu8tS9YNq5OdMLa8968lD8Q',
    appId: '1:700039457549:web:9696d9559722343bee1e44',
    messagingSenderId: '700039457549',
    projectId: 'untitled-1-a4ab0',
    authDomain: 'untitled-1-a4ab0.firebaseapp.com',
    storageBucket: 'untitled-1-a4ab0.firebasestorage.app',
    measurementId: 'G-1J1MDFFKC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGyKro57DoS8xsGM_-ALpN00As0GwzqlA',
    appId: '1:700039457549:android:d90d9013ad947c64ee1e44',
    messagingSenderId: '700039457549',
    projectId: 'untitled-1-a4ab0',
    storageBucket: 'untitled-1-a4ab0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRdQMjLsVW3JapzqVSLBgJ54IECURjnfQ',
    appId: '1:700039457549:ios:2072e572f5ae18c6ee1e44',
    messagingSenderId: '700039457549',
    projectId: 'untitled-1-a4ab0',
    storageBucket: 'untitled-1-a4ab0.firebasestorage.app',
    iosBundleId: 'com.drconnect.drConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRdQMjLsVW3JapzqVSLBgJ54IECURjnfQ',
    appId: '1:700039457549:ios:2072e572f5ae18c6ee1e44',
    messagingSenderId: '700039457549',
    projectId: 'untitled-1-a4ab0',
    storageBucket: 'untitled-1-a4ab0.firebasestorage.app',
    iosBundleId: 'com.drconnect.drConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMj4rXwgFADu8tS9YNq5OdMLa8968lD8Q',
    appId: '1:700039457549:web:3788b7d51241ee1fee1e44',
    messagingSenderId: '700039457549',
    projectId: 'untitled-1-a4ab0',
    authDomain: 'untitled-1-a4ab0.firebaseapp.com',
    storageBucket: 'untitled-1-a4ab0.firebasestorage.app',
    measurementId: 'G-72ZMFZS7SH',
  );

}